### ISSUE TITLE
Rotate text and icons

### ISSUE THREAD

**Issue by elblogbruno** [dudeofawesome/CardboardHome#6]
Hi !
I'm not an android programer,and I need this app to be modified.I want the text and icons on the app to be rotated
Thanks

**Comment by dudeofawesome** [comment]
Hey, I don't really have time right now to do this for you, but I can point you in the right direction. 
- Here's the Javadoc on [Canvas](http://docs.oracle.com/javase/8/docs/api/java/awt/Canvas.html) rotation http://docs.oracle.com/javase/8/docs/api/java/awt/Graphics2D.html#rotate-double-
- [Here's a SO question that should help explain how to do rotation](http://stackoverflow.com/questions/11553387/canvas-rotate-call-is-causing-drawn-items-to-disappear)
- [Here's the method that you would need to modify](https://github.com/dudeofawesome/CardboardHome/blob/master/app/src/main/java/dudeofawesome/cardboardhome/Launcher.java#L721)

I hope this helps. Good luck on your project!
